// 100 diverse sample articles for vector search demo
export interface Article {
  title: string
  author: string
  category: string
  tags: string
  content: string
}

export const ARTICLES: Article[] = [
  // 1-15: Original set
  { title: 'Introduction to Machine Learning', author: 'Alice Chen', category: 'Technology', tags: 'beginner,ai,tutorial', content: 'Machine learning is a branch of artificial intelligence that focuses on building systems that learn from data. Unlike traditional programming where rules are explicitly coded, machine learning algorithms identify patterns in data and use them to make predictions or decisions. The field encompasses supervised learning, where models train on labeled examples, unsupervised learning for discovering hidden structures, and reinforcement learning where agents learn through trial and error in an environment.' },
  { title: 'The Art of French Pastry', author: 'Pierre Dubois', category: 'Cooking', tags: 'baking,french,dessert', content: 'French pastry is built on precise technique and quality ingredients. The foundation starts with mastering five mother doughs: pate brisee, pate sucree, pate sablee, pate feuilletee, and pate a choux. Temperature control is critical — butter must stay cold for laminated doughs but warm for creaming methods. A proper croissant requires 27 layers of butter and dough achieved through a series of folds called turns, then a long cold proof to develop flavor while keeping the layers distinct.' },
  { title: 'Volcanic Activity on Io', author: 'Maria Santos', category: 'Astronomy', tags: 'space,jupiter,geology', content: 'Io, the innermost of Jupiter\'s four Galilean moons, is the most volcanically active body in the solar system. Tidal heating caused by gravitational interactions with Jupiter and the other large moons generates enormous internal energy, driving over 400 active volcanoes. Eruptions on Io can send plumes of sulfur dioxide hundreds of kilometers above the surface, making it one of the youngest surfaces in the solar system.' },
  { title: 'History of the Silk Road', author: 'David Kim', category: 'History', tags: 'trade,ancient,culture', content: 'The Silk Road was a network of ancient trade routes connecting China to the Mediterranean, active from roughly 130 BCE to 1453 CE. Far more than a conduit for silk and spices, it facilitated the exchange of religions, technologies, diseases, and cultural practices across Eurasia. Buddhism spread from India to China along its paths, while papermaking and gunpowder traveled westward. Caravanserais provided shelter every 30 to 40 kilometers.' },
  { title: 'Jazz Improvisation Techniques', author: 'Olga Petrova', category: 'Music', tags: 'music,theory,performance', content: 'Jazz improvisation is the art of spontaneous musical composition performed in real time. Musicians internalize chord progressions, scales, and rhythmic patterns so deeply that they can create new melodies on the fly while maintaining harmonic coherence with the ensemble. Techniques include chord-scale theory, bebop patterns that use chromatic passing tones to outline harmony, and motivic development where a simple musical idea is transformed through repetition and rhythmic variation.' },
  { title: 'Marine Biology of Coral Reefs', author: 'James Okafor', category: 'Biology', tags: 'ocean,ecology,wildlife', content: 'Coral reefs occupy less than one percent of the ocean floor but support roughly twenty-five percent of all marine species. These underwater ecosystems are built by tiny coral polyps that secrete calcium carbonate skeletons over centuries. The symbiotic relationship between corals and zooxanthellae algae is fundamental — the algae provide up to ninety percent of the coral\'s energy through photosynthesis in exchange for shelter.' },
  { title: 'Renaissance Architecture in Florence', author: 'Yuki Tanaka', category: 'Architecture', tags: 'art,italy,design', content: 'Florence became the cradle of Renaissance architecture in the fifteenth century, pioneered by Filippo Brunelleschi. His dome for the Cathedral of Santa Maria del Fiore solved an engineering problem that had stymied builders for over a century: spanning a 42-meter octagonal void without traditional centering. Brunelleschi invented a double-shell design with herringbone brickwork that was self-supporting during construction.' },
  { title: 'Olympic Weightlifting Fundamentals', author: 'Fatima Al-Hassan', category: 'Sports', tags: 'fitness,strength,competition', content: 'Olympic weightlifting consists of two competition lifts: the snatch and the clean and jerk. The snatch requires explosive power to move the barbell from floor to overhead in one continuous motion, demanding exceptional hip mobility, shoulder stability, and timing. Success depends on the triple extension of ankles, knees, and hips generating maximum vertical force in milliseconds.' },
  { title: 'The Economics of Carbon Markets', author: 'Alice Chen', category: 'Economics', tags: 'climate,finance,policy', content: 'Carbon markets put a price on greenhouse gas emissions to incentivize reduction. Cap-and-trade systems set an overall emissions limit, distribute allowances, and let companies trade them. The European Union Emissions Trading System, launched in 2005, is the largest, covering about forty percent of EU emissions. Carbon prices have risen from under five euros per ton to over ninety euros, fundamentally changing investment decisions.' },
  { title: 'Fermentation and Sourdough Bread', author: 'Pierre Dubois', category: 'Food Science', tags: 'fermentation,baking,microbiology', content: 'Sourdough fermentation relies on a symbiotic culture of wild yeasts and lactic acid bacteria maintained in a starter. Unlike commercial yeast which produces mainly carbon dioxide, sourdough cultures create a complex mix of organic acids, alcohols, and flavor compounds over a twelve to forty-eight hour fermentation. Lactobacillus bacteria lower the pH to around 3.5 to 4.0, activating phytase enzymes that break down phytic acid.' },
  { title: 'Urban Planning in Tokyo', author: 'Yuki Tanaka', category: 'Urban Design', tags: 'cities,japan,transit', content: 'Tokyo\'s urban planning combines extreme density with remarkable livability through its integrated transit-oriented development model. The city\'s rail network carries over forty million passengers daily across a web of public and private lines. Zoning laws allow mixed-use development near stations while preserving low-rise residential neighborhoods. The concept of depachika — elaborate basement food halls connected directly to train stations — exemplifies seamless urban fabric.' },
  { title: 'Cognitive Behavioral Therapy', author: 'Maria Santos', category: 'Psychology', tags: 'mental-health,therapy,science', content: 'Cognitive behavioral therapy is based on the principle that thoughts, feelings, and behaviors are interconnected, and that changing maladaptive thinking patterns can improve emotional regulation and behavior. A core technique is cognitive restructuring, where patients learn to identify automatic negative thoughts, examine the evidence for and against them, and develop more balanced alternatives.' },
  { title: 'Beekeeping for Beginners', author: 'James Okafor', category: 'Agriculture', tags: 'insects,nature,hobby', content: 'Beekeeping requires understanding the social structure of a honey bee colony, which consists of a single queen, thousands of female workers, and a small number of male drones. The queen can lay up to two thousand eggs per day during peak season. Workers rotate through age-dependent roles: nursing brood, building comb from secreted beeswax, processing nectar into honey, guarding the entrance, and finally foraging.' },
  { title: 'The Physics of Black Holes', author: 'David Kim', category: 'Physics', tags: 'cosmology,relativity,science', content: 'Black holes form when massive stars exhaust their nuclear fuel and collapse under their own gravity. The boundary beyond which nothing can escape is called the event horizon, and at the center lies a singularity where density becomes theoretically infinite. In 2019, the Event Horizon Telescope captured the first direct image of a black hole\'s shadow in the galaxy M87, confirming predictions of general relativity.' },
  { title: 'Ancient Egyptian Hieroglyphics', author: 'Olga Petrova', category: 'Archaeology', tags: 'writing,language,ancient', content: 'Ancient Egyptian hieroglyphics represent one of the earliest writing systems, dating to approximately 3200 BCE. The script combines logographic and alphabetic elements: some signs represent whole words or concepts while others denote individual consonant sounds. The Rosetta Stone, discovered in 1799, provided the key to decipherment by presenting the same text in hieroglyphics, Demotic script, and ancient Greek.' },

  // 16-30: Earth & Environmental Sciences
  { title: 'Plate Tectonics and Continental Drift', author: 'Raj Patel', category: 'Geology', tags: 'earth,plates,earthquakes', content: 'Plate tectonics describes the large-scale motion of Earth\'s lithosphere, divided into rigid plates that float on the semi-fluid asthenosphere beneath. Where plates collide, one may subduct beneath the other, creating deep ocean trenches and volcanic arcs. Where they diverge, magma rises to form new crust at mid-ocean ridges. The theory explains the distribution of earthquakes, volcanoes, and mountain ranges across the globe.' },
  { title: 'The Water Cycle and Climate', author: 'Elena Volkov', category: 'Environmental Science', tags: 'water,climate,atmosphere', content: 'The water cycle drives weather patterns and sustains life through continuous evaporation, condensation, and precipitation. Solar energy heats surface water, converting it to vapor that rises and cools to form clouds. Precipitation returns water to the surface, where it flows through rivers, percolates into groundwater, or collects in lakes and oceans. Climate change is intensifying this cycle, producing more extreme droughts and floods.' },
  { title: 'Tropical Rainforest Ecosystems', author: 'Amara Diallo', category: 'Ecology', tags: 'rainforest,biodiversity,tropics', content: 'Tropical rainforests cover only six percent of Earth\'s surface but contain more than half of all terrestrial species. The canopy structure creates distinct vertical layers — emergent trees reaching sixty meters, a dense canopy at thirty meters, an understory of shade-tolerant species, and a forest floor receiving less than two percent of sunlight. Nutrient cycling is rapid: decomposing matter is absorbed almost immediately by shallow root networks.' },
  { title: 'Glaciology and Ice Sheet Dynamics', author: 'Sven Lindqvist', category: 'Earth Science', tags: 'glaciers,ice,climate', content: 'Glaciers form when accumulated snowfall compresses into dense ice over decades. These ice masses flow under their own weight, carving valleys, transporting sediment, and shaping landscapes. The Greenland and Antarctic ice sheets together contain enough water to raise global sea levels by over sixty-five meters. Satellite measurements show both sheets losing mass at accelerating rates, with calving icebergs and basal melting driven by warming ocean currents.' },
  { title: 'Soil Science and Agriculture', author: 'Priya Sharma', category: 'Agriculture', tags: 'soil,farming,nutrients', content: 'Healthy soil is a complex ecosystem containing minerals, organic matter, water, air, and billions of organisms per gram. Soil horizons develop over centuries as weathering breaks down rock and organic material accumulates. Mycorrhizal fungi form symbiotic networks with plant roots, extending their reach and exchanging phosphorus for carbon. Modern agriculture disrupts these systems through tillage and synthetic fertilizers, but regenerative practices like cover cropping and no-till farming can restore soil health.' },

  // 31-45: Technology & Computing
  { title: 'How Cryptographic Hash Functions Work', author: 'Alice Chen', category: 'Computer Science', tags: 'cryptography,security,algorithms', content: 'Cryptographic hash functions transform arbitrary input data into a fixed-length digest that appears random but is deterministic. A good hash function is preimage-resistant (you cannot reverse it), collision-resistant (two different inputs should not produce the same hash), and exhibits the avalanche effect where a single bit change in input completely alters the output. SHA-256 produces a 256-bit hash used in digital signatures, blockchain, and password storage.' },
  { title: 'The Architecture of Modern CPUs', author: 'Wei Zhang', category: 'Hardware', tags: 'cpu,architecture,computing', content: 'Modern CPUs achieve performance through instruction-level parallelism, executing multiple operations per clock cycle via pipelining and superscalar design. Branch prediction algorithms guess which path conditional code will take, speculatively executing instructions to avoid pipeline stalls. Cache hierarchies — L1, L2, and L3 — keep frequently accessed data close to execution units, since main memory access is roughly a hundred times slower than an L1 cache hit.' },
  { title: 'Database Indexing Strategies', author: 'Fatima Al-Hassan', category: 'Databases', tags: 'database,indexing,performance', content: 'Database indexes accelerate queries by maintaining sorted references to table rows, trading write performance and storage for dramatically faster reads. B-tree indexes handle range queries efficiently with logarithmic lookup time. Hash indexes provide constant-time exact-match lookups but cannot support range scans. Composite indexes on multiple columns optimize queries that filter on specific column combinations, but column order matters — the index is only useful when queries filter on a prefix of the indexed columns.' },
  { title: 'Introduction to Quantum Computing', author: 'Raj Patel', category: 'Technology', tags: 'quantum,computing,physics', content: 'Quantum computers use qubits that can exist in superposition — simultaneously representing both zero and one — unlike classical bits. Entanglement allows qubits to be correlated in ways that have no classical equivalent, enabling quantum parallelism. Shor\'s algorithm can factor large numbers exponentially faster than classical methods, threatening current encryption. Grover\'s algorithm provides quadratic speedup for unstructured search. Current quantum computers are noisy and require error correction.' },
  { title: 'Distributed Systems Consensus', author: 'Alice Chen', category: 'Computer Science', tags: 'distributed,consensus,networking', content: 'Achieving consensus in distributed systems where nodes can fail is one of computing\'s fundamental challenges. The Raft algorithm elects a leader that manages log replication across followers, maintaining consistency even when minority nodes crash. Paxos provides similar guarantees with different trade-offs. Byzantine fault tolerance algorithms like PBFT handle malicious nodes but require three-times-f-plus-one nodes to tolerate f failures, making them expensive at scale.' },
  { title: 'Neural Network Architectures', author: 'Wei Zhang', category: 'AI', tags: 'deep-learning,neural-networks,ai', content: 'Convolutional neural networks excel at spatial pattern recognition by applying learned filters across input data, detecting features like edges, textures, and shapes at progressively higher abstraction levels. Recurrent networks process sequential data by maintaining hidden state across time steps. Transformers replaced recurrence with self-attention mechanisms that relate every position in a sequence to every other, enabling massive parallelism and powering modern language models.' },
  { title: 'WebAssembly and the Browser Runtime', author: 'Yuki Tanaka', category: 'Web Development', tags: 'wasm,browser,performance', content: 'WebAssembly is a binary instruction format designed as a portable compilation target for languages like C, Rust, and Go. It runs in a sandboxed virtual machine at near-native speed, complementing JavaScript for compute-intensive tasks. WASM modules are loaded and instantiated by the browser, communicating with JavaScript through imported and exported functions. Use cases include image processing, physics simulations, cryptography, and porting existing native applications to the web.' },

  // 46-60: Life Sciences & Medicine
  { title: 'How mRNA Vaccines Work', author: 'Elena Volkov', category: 'Medicine', tags: 'vaccines,mrna,immunology', content: 'mRNA vaccines deliver synthetic messenger RNA encoding a target protein — typically a viral surface protein — into cells. Ribosomes translate the mRNA into protein, which is displayed on the cell surface. The immune system recognizes these proteins as foreign and mounts a response, producing antibodies and training T cells. The mRNA degrades within days, leaving no permanent genetic material. Lipid nanoparticles protect the fragile mRNA during delivery and facilitate cell uptake.' },
  { title: 'Photosynthesis in C4 Plants', author: 'Amara Diallo', category: 'Botany', tags: 'plants,photosynthesis,biology', content: 'C4 photosynthesis is an evolutionary adaptation that concentrates carbon dioxide around the enzyme RuBisCO, suppressing wasteful photorespiration. Plants like corn, sugarcane, and sorghum fix CO2 initially into a four-carbon compound in mesophyll cells, then shuttle it to bundle sheath cells where the Calvin cycle operates at high CO2 concentration. This mechanism evolved independently over sixty times across plant lineages, conferring advantages in hot, dry, and high-light environments.' },
  { title: 'The Human Microbiome', author: 'Priya Sharma', category: 'Microbiology', tags: 'microbiome,gut,health', content: 'The human body hosts trillions of microorganisms — bacteria, fungi, viruses, and archaea — collectively called the microbiome. The gut alone contains over a thousand bacterial species weighing roughly two kilograms. These microbes digest fiber into short-chain fatty acids, synthesize vitamins B and K, train the immune system, and influence mood through the gut-brain axis via vagus nerve signaling and neurotransmitter production. Antibiotic use, diet, and birth method shape microbiome composition.' },
  { title: 'CRISPR Gene Editing Explained', author: 'Maria Santos', category: 'Genetics', tags: 'crispr,genetics,biotechnology', content: 'CRISPR-Cas9 is a gene editing tool adapted from a bacterial immune defense. A guide RNA directs the Cas9 enzyme to a specific DNA sequence, where it creates a double-strand break. The cell\'s repair machinery then either disrupts the gene through imprecise repair or inserts a new sequence via homology-directed repair with a supplied template. Applications span medicine, agriculture, and research, though off-target edits and ethical concerns about germline modifications remain active areas of debate.' },
  { title: 'Neuroscience of Memory Formation', author: 'Olga Petrova', category: 'Neuroscience', tags: 'brain,memory,cognition', content: 'Memory formation involves three stages: encoding, consolidation, and retrieval. The hippocampus plays a central role in converting short-term memories into long-term storage through a process called long-term potentiation, where repeated neural firing strengthens synaptic connections. During sleep, the brain replays daily experiences, transferring memories from hippocampal to neocortical storage. Emotional memories are enhanced by amygdala activation, which modulates hippocampal encoding through stress hormone signaling.' },
  { title: 'Antibiotic Resistance Mechanisms', author: 'Elena Volkov', category: 'Microbiology', tags: 'antibiotics,resistance,bacteria', content: 'Bacteria develop antibiotic resistance through mutation and horizontal gene transfer via plasmids, transposons, and bacteriophages. Resistance mechanisms include enzyme production that degrades the antibiotic (like beta-lactamases breaking penicillin), efflux pumps that expel drugs from the cell, modification of the drug target site, and metabolic bypass pathways. Biofilm formation provides additional protection by creating a physical barrier and enabling persister cells that tolerate antibiotics without genetic resistance.' },
  { title: 'Evolution of Flight in Birds', author: 'James Okafor', category: 'Zoology', tags: 'birds,evolution,paleontology', content: 'The evolution of flight in birds traces back to small feathered theropod dinosaurs in the Late Jurassic. Archaeopteryx, dating to 150 million years ago, had flight feathers and a wishbone but retained teeth and a bony tail. Modern bird flight depends on hollow pneumatized bones reducing weight, a keeled sternum anchoring powerful flight muscles, and asymmetric feathers generating lift. The respiratory system uses air sacs for continuous unidirectional airflow, providing oxygen efficiency unmatched by mammalian lungs.' },
  { title: 'Cellular Respiration Pathways', author: 'Priya Sharma', category: 'Biochemistry', tags: 'metabolism,energy,cells', content: 'Cellular respiration extracts energy from glucose through three main stages. Glycolysis splits glucose into two pyruvate molecules in the cytoplasm, yielding a net two ATP. The citric acid cycle in the mitochondrial matrix oxidizes acetyl-CoA, generating electron carriers NADH and FADH2. The electron transport chain on the inner mitochondrial membrane uses these carriers to pump protons, creating a gradient that drives ATP synthase to produce roughly thirty-four ATP per glucose molecule.' },

  // 61-75: Arts, Culture & Humanities
  { title: 'The Golden Ratio in Art and Nature', author: 'Yuki Tanaka', category: 'Mathematics', tags: 'math,art,nature', content: 'The golden ratio, approximately 1.618, appears throughout nature in the spiral arrangement of sunflower seeds, nautilus shell chambers, and hurricane cloud bands. Renaissance artists like Leonardo da Vinci deliberately employed it in compositions, and the Parthenon\'s facade closely approximates golden proportions. The ratio emerges from the Fibonacci sequence where each number is the sum of the two preceding ones — the ratio of consecutive terms converges to phi as the sequence grows.' },
  { title: 'History of Typography', author: 'Pierre Dubois', category: 'Design', tags: 'typography,design,printing', content: 'Typography began with Gutenberg\'s movable type press around 1440, using blackletter typefaces that mimicked medieval handwriting. Roman type appeared in Italy by 1470, inspired by classical inscriptions. Claude Garamond created influential old-style serifs in the sixteenth century. The industrial revolution brought sans-serif faces and wood type for large display use. Digital typography liberated type design from physical constraints, enabling variable fonts that smoothly interpolate between weights and widths.' },
  { title: 'Japanese Wabi-Sabi Aesthetics', author: 'Yuki Tanaka', category: 'Philosophy', tags: 'japan,aesthetics,culture', content: 'Wabi-sabi is a Japanese aesthetic philosophy rooted in Zen Buddhism that finds beauty in imperfection, impermanence, and incompleteness. Wabi originally meant the melancholy of living in nature, while sabi referred to the beauty of aging and wear. Together they value asymmetry, roughness, simplicity, and the patina of time. Kintsugi — repairing broken pottery with gold lacquer — embodies wabi-sabi by celebrating damage as part of an object\'s history rather than concealing it.' },
  { title: 'The Physics of Musical Instruments', author: 'David Kim', category: 'Acoustics', tags: 'music,physics,sound', content: 'Musical instruments produce sound through vibrating strings, air columns, membranes, or solid bodies. A guitar string vibrates at a fundamental frequency determined by its length, tension, and mass per unit length, along with harmonic overtones at integer multiples. The instrument body amplifies these vibrations through resonance, and its shape determines which harmonics are emphasized — giving each instrument its characteristic timbre. Wind instruments use standing waves in air columns, with tone holes or valves changing the effective column length.' },
  { title: 'Mesoamerican Civilization and Calendar', author: 'Maria Santos', category: 'Anthropology', tags: 'maya,calendar,civilization', content: 'The Maya developed one of the ancient world\'s most sophisticated calendar systems, combining a 260-day ritual calendar (Tzolkin) with a 365-day solar calendar (Haab) into a Calendar Round that repeats every 52 years. For longer periods, they used the Long Count, a linear day count from a mythological creation date. Maya mathematics used a vigesimal (base-20) system with a concept of zero centuries before its adoption in the Old World, enabling astronomical calculations of remarkable precision.' },
  { title: 'Film Noir Cinematography', author: 'Olga Petrova', category: 'Cinema', tags: 'film,noir,cinematography', content: 'Film noir emerged in 1940s Hollywood, characterized by low-key lighting with strong contrasts between light and shadow. Cinematographers used hard directional lighting to create dramatic shadows, venetian blind patterns, and silhouettes that externalized characters\' psychological states. Dutch angles conveyed moral disorientation, while deep focus kept both foreground and background sharp, trapping characters in oppressive environments. The visual style drew from German Expressionism and was reinforced by post-war anxieties about corruption and moral ambiguity.' },
  { title: 'Sanskrit and Indo-European Languages', author: 'Raj Patel', category: 'Linguistics', tags: 'language,sanskrit,indo-european', content: 'Sanskrit belongs to the Indo-European language family, sharing common ancestry with Latin, Greek, Persian, and most European languages. The systematic grammar described by Panini around 400 BCE in his Ashtadhyayi — containing roughly 4,000 rules — influenced modern linguistics and even early computer science. Cognates reveal the family connection: Sanskrit "mata" corresponds to Latin "mater," Greek "meter," and English "mother," all descending from a reconstructed Proto-Indo-European root.' },
  { title: 'The Art of Pottery and Ceramics', author: 'Amara Diallo', category: 'Crafts', tags: 'pottery,ceramics,art', content: 'Pottery is one of humanity\'s oldest technologies, with fired clay vessels dating to 20,000 years ago in East Asia. The potter\'s wheel, invented around 3500 BCE in Mesopotamia, enabled symmetrical forms and faster production. Clay bodies range from earthenware fired below 1150 degrees Celsius to stoneware and porcelain requiring temperatures above 1260 degrees. Glazes — mixtures of silica, flux, and colorants — melt during firing to create a glassy surface that is both decorative and functional.' },
  { title: 'Baroque Music and Bach', author: 'David Kim', category: 'Music History', tags: 'baroque,bach,classical', content: 'The Baroque period in music (1600-1750) established tonal harmony, basso continuo, and elaborate ornamentation as defining features. Johann Sebastian Bach synthesized Italian, French, and German styles into works of unmatched contrapuntal complexity. His Well-Tempered Clavier demonstrated that keyboards could play expressively in all 24 major and minor keys. Bach\'s fugues layer independent melodic lines that follow strict rules of imitation while creating rich harmonic textures, influencing composers for centuries.' },
  { title: 'Aboriginal Australian Dreamtime', author: 'Sven Lindqvist', category: 'Cultural Studies', tags: 'aboriginal,dreamtime,australia', content: 'The Dreamtime, or Dreaming, is the foundational spiritual framework of Aboriginal Australian cultures, describing the era when ancestral beings shaped the landscape, established laws, and created life. These narratives are not merely mythology but constitute a living legal, ecological, and moral system. Songlines — paths across the land marked by songs — encode navigation routes, water sources, and territorial boundaries, functioning as oral maps that have guided travel across the continent for over 60,000 years.' },

  // 76-90: Engineering & Applied Sciences
  { title: 'How Nuclear Reactors Generate Power', author: 'Wei Zhang', category: 'Energy', tags: 'nuclear,energy,engineering', content: 'Nuclear fission reactors split heavy atoms — typically uranium-235 or plutonium-239 — by bombarding them with neutrons. Each fission event releases roughly 200 MeV of energy and two to three additional neutrons, sustaining a chain reaction. Control rods made of neutron-absorbing materials like boron regulate the reaction rate. The heat generated boils water into steam that drives turbines. Pressurized water reactors keep the primary coolant under 155 atmospheres to prevent boiling in the reactor core.' },
  { title: 'Bridge Engineering and Load Paths', author: 'Fatima Al-Hassan', category: 'Civil Engineering', tags: 'bridges,structures,engineering', content: 'Bridge design routes gravitational and live loads through structural members to foundations. Beam bridges resist loads through bending, with tension on the bottom flange and compression on top. Arch bridges convert vertical loads into compressive thrust along the curve, pushing outward at the abutments. Suspension bridges transfer deck loads through vertical hangers to main cables in tension, which pull inward at anchorages. Cable-stayed bridges use diagonal cables from towers directly to the deck, creating a self-anchored system.' },
  { title: 'Aerodynamics of Airplane Wings', author: 'Sven Lindqvist', category: 'Aerospace', tags: 'aviation,aerodynamics,flight', content: 'Airplane wings generate lift through their airfoil shape, which accelerates air over the curved upper surface relative to the flatter lower surface. The resulting pressure difference produces an upward force. At higher angles of attack, lift increases until the boundary layer separates and the wing stalls. Wing design involves trade-offs: swept wings reduce drag at transonic speeds, high-aspect-ratio wings minimize induced drag for efficient cruising, and winglets reduce tip vortices that waste energy.' },
  { title: 'Wastewater Treatment Processes', author: 'Priya Sharma', category: 'Environmental Engineering', tags: 'water,treatment,sanitation', content: 'Wastewater treatment proceeds through primary, secondary, and tertiary stages. Primary treatment uses screens and settling tanks to remove large solids and suspended matter by gravity. Secondary treatment employs biological processes — activated sludge or trickling filters — where microorganisms consume dissolved organic compounds. Tertiary treatment removes remaining nutrients like nitrogen and phosphorus through chemical precipitation or biological nutrient removal, followed by disinfection with chlorine, UV, or ozone before discharge.' },
  { title: 'Steel Metallurgy and Alloys', author: 'Wei Zhang', category: 'Materials Science', tags: 'steel,metallurgy,materials', content: 'Steel is an alloy of iron and carbon (typically 0.2 to 2.1 percent by weight), with properties dramatically altered by composition and heat treatment. Quenching from high temperature traps carbon in a body-centered tetragonal martensite structure, creating extreme hardness but brittleness. Tempering reheats martensite to allow partial carbon diffusion, balancing hardness with toughness. Alloying elements serve specific roles: chromium above 10.5% creates stainless steel by forming a passive oxide layer, while manganese improves wear resistance.' },
  { title: 'Rocket Propulsion Fundamentals', author: 'Raj Patel', category: 'Aerospace', tags: 'rockets,propulsion,space', content: 'Rocket engines generate thrust by expelling mass at high velocity, governed by Newton\'s third law. The Tsiolkovsky rocket equation relates final velocity to exhaust velocity and the ratio of initial to final mass, imposing the tyranny of the rocket equation: most of a rocket\'s mass must be propellant. Liquid engines like the Raptor burn methane and oxygen in a staged combustion cycle for high efficiency. Solid rockets offer simplicity and storage advantages but cannot be throttled or shut down once ignited.' },
  { title: 'Textile Manufacturing and Fibers', author: 'Amara Diallo', category: 'Manufacturing', tags: 'textiles,fibers,manufacturing', content: 'Textile production transforms raw fibers into fabric through spinning, weaving or knitting, and finishing. Natural fibers include cellulose-based cotton and linen, and protein-based wool and silk. Synthetic fibers like polyester and nylon are melt-spun from petrochemical polymers through spinnerets. Weaving interlaces warp and weft threads on a loom — plain weave, twill, and satin are the three fundamental structures. Finishing processes including mercerization, calendering, and dyeing determine the fabric\'s final hand, luster, and color.' },
  { title: 'Refrigeration and Heat Pumps', author: 'Elena Volkov', category: 'Mechanical Engineering', tags: 'hvac,thermodynamics,cooling', content: 'Refrigeration cycles move heat from cold spaces to warm ones using the thermodynamic properties of phase-changing refrigerants. A compressor pressurizes gas refrigerant, raising its temperature. The hot gas releases heat in the condenser, condensing to liquid. An expansion valve drops the pressure, cooling the liquid dramatically. The cold refrigerant absorbs heat in the evaporator, boiling back to gas. Heat pumps use the same cycle in reverse, extracting heat from outdoor air or ground and delivering it indoors, achieving efficiencies of 300 to 500 percent.' },
  { title: 'Optical Fiber Communication', author: 'Alice Chen', category: 'Telecommunications', tags: 'fiber-optics,networking,light', content: 'Optical fibers transmit data as pulses of light through thin glass strands using total internal reflection. Single-mode fibers with 9-micrometer cores carry signals over hundreds of kilometers with minimal dispersion, while multi-mode fibers with larger cores serve shorter distances. Wavelength-division multiplexing sends multiple signals simultaneously on different light wavelengths through the same fiber, achieving aggregate bandwidths exceeding 100 terabits per second. Erbium-doped fiber amplifiers boost signals optically without converting to electronic form.' },
  { title: 'Earthquake-Resistant Building Design', author: 'Fatima Al-Hassan', category: 'Structural Engineering', tags: 'earthquakes,buildings,safety', content: 'Earthquake-resistant design manages seismic energy through three strategies: strength (resisting forces), ductility (deforming without collapse), and isolation (decoupling the building from ground motion). Base isolators — rubber and steel bearings — allow the foundation to move independently of the superstructure. Tuned mass dampers — heavy pendulums near the top of tall buildings — counteract sway. Moment-resisting steel frames flex without breaking, while shear walls and braced frames provide lateral stiffness. Japan\'s building codes require structures to survive severe shaking without collapse.' },

  // 91-100: Miscellaneous & Interdisciplinary
  { title: 'The Science of Sleep', author: 'Olga Petrova', category: 'Neuroscience', tags: 'sleep,brain,health', content: 'Sleep proceeds through four to six ninety-minute cycles of NREM and REM stages each night. Slow-wave deep sleep dominates early cycles, during which the glymphatic system clears metabolic waste — including amyloid beta associated with Alzheimer\'s — from the brain. REM sleep increases in later cycles, characterized by rapid eye movements, muscle paralysis, and vivid dreaming. During REM, the brain consolidates procedural and emotional memories while the prefrontal cortex is largely offline, explaining dream illogic.' },
  { title: 'Cheese Making and Microbiology', author: 'Pierre Dubois', category: 'Food Science', tags: 'cheese,fermentation,dairy', content: 'Cheese making begins by acidifying milk with bacterial starter cultures that convert lactose to lactic acid. Rennet — an enzyme complex traditionally from calf stomachs — coagulates casein proteins into a gel that is cut into curds. Whey is drained and curds are pressed, salted, and aged. Specific bacterial and fungal cultures create distinctive varieties: Penicillium roqueforti produces blue cheese veining, Propionibacterium freudenreichii generates the carbon dioxide bubbles in Swiss cheese, and Brevibacterium linens creates washed-rind flavors.' },
  { title: 'Map Projections and Cartography', author: 'Sven Lindqvist', category: 'Geography', tags: 'maps,cartography,geography', content: 'Every map projection distorts the spherical Earth when flattening it to two dimensions, preserving some properties while sacrificing others. The Mercator projection preserves angles for navigation but grotesquely inflates polar regions — Greenland appears as large as Africa despite being fourteen times smaller. Equal-area projections like Mollweide preserve relative sizes but distort shapes. The Robinson projection compromises on all properties to produce a visually pleasing world map. Modern GIS systems store data in unprojected coordinates and project on the fly.' },
  { title: 'Origami Mathematics', author: 'Yuki Tanaka', category: 'Mathematics', tags: 'origami,geometry,folding', content: 'Mathematical origami explores the geometry of paper folding, revealing that flat folds satisfy the Kawasaki-Justin theorem: alternating angles around any interior vertex must sum to 180 degrees. Origami axioms — the Huzita-Hatori axioms — are more powerful than compass-and-straightedge constructions, enabling trisection of angles and doubling of cubes that are impossible with classical tools. Engineering applications include deployable solar panels that unfold from compact stowed configurations using Miura fold patterns, and stent designs that expand inside blood vessels.' },
  { title: 'Coffee Cultivation and Processing', author: 'Amara Diallo', category: 'Agriculture', tags: 'coffee,farming,processing', content: 'Coffee grows as a cherry on evergreen shrubs in the tropical belt between the Tropics of Cancer and Capricorn, at elevations between 600 and 2000 meters. Arabica, accounting for sixty percent of production, requires cooler temperatures and higher altitude than Robusta. Processing methods profoundly affect flavor: washed (wet) processing removes mucilage before drying for clean bright cups, natural (dry) processing dries cherries whole for fruity sweetness, and honey processing removes skin but leaves mucilage for balanced complexity.' },
  { title: 'Game Theory and Nash Equilibrium', author: 'David Kim', category: 'Economics', tags: 'game-theory,strategy,math', content: 'Game theory analyzes strategic interactions where each participant\'s outcome depends on others\' choices. A Nash equilibrium exists when no player can improve their payoff by unilaterally changing strategy. The Prisoner\'s Dilemma illustrates how individually rational choices lead to collectively suboptimal outcomes — both players defect despite mutual cooperation yielding higher payoffs. Repeated games introduce reputation effects that can sustain cooperation. Applications span economics, political science, evolutionary biology, and auction design.' },
  { title: 'Traditional Chinese Medicine Principles', author: 'Wei Zhang', category: 'Medicine', tags: 'tcm,herbal,wellness', content: 'Traditional Chinese medicine is built on the concept of qi — vital energy flowing through meridian channels — and the balance of yin and yang, opposing forces whose harmony maintains health. Diagnosis involves observing the tongue, palpating the pulse at multiple positions, and evaluating symptoms through pattern differentiation. Treatment modalities include herbal formulas combining multiple plants for synergistic effects, acupuncture inserting needles at specific points to redirect qi flow, and practices like tai chi and qigong that cultivate internal energy through movement and breathing.' },
  { title: 'The Chemistry of Fireworks', author: 'Elena Volkov', category: 'Chemistry', tags: 'fireworks,chemistry,pyrotechnics', content: 'Fireworks produce colors through metal salt combustion: strontium compounds burn red, barium salts green, copper compounds blue, and sodium yellow. A shell contains a lifting charge of black powder, a time-delay fuse, and a burst charge surrounding pellets called stars. When the burst charge ignites, it scatters the stars outward in patterns determined by their arrangement — spherical for peonies, trailing for willows. Achieving a true blue remains the hardest challenge because copper chloride decomposes at the temperatures needed for brightness.' },
  { title: 'Permaculture Design Principles', author: 'James Okafor', category: 'Sustainability', tags: 'permaculture,sustainability,design', content: 'Permaculture designs productive ecosystems by observing and mimicking natural patterns. The core ethics — earth care, people care, and fair share — guide twelve design principles including catching and storing energy, obtaining a yield, and using edges and valuing the marginal. Food forests layer canopy trees, understory trees, shrubs, herbs, ground cover, root crops, and vines to create self-maintaining polycultures. Swales — contour trenches — capture rainwater and direct it to tree roots, turning slopes into productive terraces without irrigation.' },
  { title: 'History of Cryptography', author: 'Alice Chen', category: 'History', tags: 'cryptography,history,codes', content: 'Cryptography evolved from simple substitution ciphers — Caesar\'s shift cipher rotating letters by three positions — to the polyalphabetic Vigenere cipher in the sixteenth century, which resisted frequency analysis. The Enigma machine used rotating electromechanical rotors to create a cipher alphabet that changed with every keystroke. Modern cryptography is founded on mathematical problems: RSA relies on the difficulty of factoring large semiprimes, while elliptic curve cryptography achieves equivalent security with smaller keys by exploiting the discrete logarithm problem on elliptic curves over finite fields.' },
]
